### ISSUE TITLE
Feature Req: support user-defined timezone aliases

### ISSUE THREAD

**Issue by theckman** [therealplato/timez#1]
I work a at a company where we have multiple offices, and people who work from home (in different timezones). It would be cool to be able to do the timezone conversion to timezones, aliased by the person's name (for example).

This could also allow someone to create their own short-hand alias for commonly-used timezones if they want.

**Comment by therealplato** [comment]
good idea, done. see https://github.com/therealplato/timez/blob/master/example.timezrc for example usage
